create table if not exists public.report_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  email text not null,
  source text not null,
  currency text not null,
  page_url text,
  page_title text,
  summary_text text not null,
  inputs_json jsonb not null default '{}'::jsonb,
  results_json jsonb not null default '{}'::jsonb,
  context_json jsonb not null default '{}'::jsonb,
  user_agent text,
  email_sent boolean not null default false,
  email_provider_id text,
  email_sent_at timestamptz,
  send_error text
);

create index if not exists report_requests_created_at_idx
  on public.report_requests (created_at desc);

create index if not exists report_requests_email_idx
  on public.report_requests (email);

alter table public.report_requests enable row level security;

